from pathlib import Path
import re
from copy import copy

from docx import Document
from pptx import Presentation
from openpyxl import Workbook


class ContentFileExportService:
    """
    Export Nova AI generated content into downloadable files.
    """

    def __init__(
        self,
        output_dir: str = "generated/content",
    ):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

    def _safe_filename(
        self,
        content_type: str,
    ) -> str:
        name = (
            str(content_type or "content")
            .strip()
            .lower()
        )

        name = re.sub(
            r"[^a-z0-9_-]+",
            "_",
            name,
        ).strip("_")

        return name or "content"

    def _safe_custom_filename(
        self,
        filename: str | None,
        fallback: str,
    ) -> str:
        if not filename:
            return fallback

        safe_name = Path(filename).stem

        safe_name = re.sub(
            r"[^a-zA-Z0-9_-]+",
            "_",
            safe_name,
        ).strip("_")

        return safe_name or fallback

    # =========================================================
    # DOCX
    # =========================================================

    def export_docx(
        self,
        content: str,
        content_type: str,
        filename: str | None = None,
    ) -> str:
        if not str(content or "").strip():
            raise ValueError(
                "Content cannot be empty."
            )

        safe_type = self._safe_filename(
            content_type
        )

        safe_name = self._safe_custom_filename(
            filename,
            f"nova_{safe_type}",
        )

        file_path = (
            self.output_dir
            / f"{safe_name}.docx"
        )

        document = Document()

        document.add_heading(
            f"Nova AI - {content_type.title()}",
            level=0,
        )

        for paragraph in str(content).split("\n"):
            document.add_paragraph(
                paragraph
            )

        document.save(file_path)

        return str(file_path)

    # =========================================================
    # PPTX
    # =========================================================

    def export_pptx(
        self,
        content: str,
        content_type: str,
        filename: str | None = None,
    ) -> str:
        if not str(content or "").strip():
            raise ValueError(
                "Content cannot be empty."
            )

        safe_type = self._safe_filename(
            content_type
        )

        safe_name = self._safe_custom_filename(
            filename,
            f"nova_{safe_type}",
        )

        file_path = (
            self.output_dir
            / f"{safe_name}.pptx"
        )

        presentation = Presentation()

        # -----------------------------------------------------
        # Title slide
        # -----------------------------------------------------

        title_layout = presentation.slide_layouts[0]

        title_slide = presentation.slides.add_slide(
            title_layout
        )

        title_slide.shapes.title.text = (
            f"Nova AI - {content_type.title()}"
        )

        if len(title_slide.placeholders) > 1:
            title_slide.placeholders[1].text = (
                "Generated by Nova AI Workspace"
            )

        # -----------------------------------------------------
        # Content slides
        # -----------------------------------------------------

        paragraphs = [
            paragraph.strip()
            for paragraph in str(content).split("\n")
            if paragraph.strip()
        ]

        if not paragraphs:
            paragraphs = [str(content).strip()]

        chunks = []
        current_chunk = []

        current_length = 0
        max_chars = 900

        for paragraph in paragraphs:
            paragraph_length = len(paragraph)

            if (
                current_chunk
                and current_length + paragraph_length > max_chars
            ):
                chunks.append(current_chunk)
                current_chunk = []
                current_length = 0

            current_chunk.append(paragraph)
            current_length += paragraph_length + 1

        if current_chunk:
            chunks.append(current_chunk)

        for index, chunk in enumerate(chunks, start=1):
            layout = presentation.slide_layouts[1]

            slide = presentation.slides.add_slide(
                layout
            )

            slide.shapes.title.text = (
                "Content"
                if len(chunks) == 1
                else f"Content - Part {index}"
            )

            text_frame = (
                slide.placeholders[1].text_frame
            )

            text_frame.clear()

            for paragraph_index, paragraph in enumerate(
                chunk
            ):
                if paragraph_index == 0:
                    text_paragraph = text_frame.paragraphs[0]
                else:
                    text_paragraph = text_frame.add_paragraph()

                text_paragraph.text = paragraph
                text_paragraph.level = 0

        presentation.save(file_path)

        return str(file_path)

    # =========================================================
    # XLSX
    # =========================================================

    def export_xlsx(
        self,
        content: str,
        content_type: str,
        filename: str | None = None,
    ) -> str:
        if not str(content or "").strip():
            raise ValueError(
                "Content cannot be empty."
            )

        safe_type = self._safe_filename(
            content_type
        )

        safe_name = self._safe_custom_filename(
            filename,
            f"nova_{safe_type}",
        )

        file_path = (
            self.output_dir
            / f"{safe_name}.xlsx"
        )

        workbook = Workbook()

        worksheet = workbook.active
        worksheet.title = "Generated Content"

        # -----------------------------------------------------
        # Title
        # -----------------------------------------------------

        worksheet["A1"] = (
            f"Nova AI - {content_type.title()}"
        )

        worksheet["A2"] = (
            "Generated by Nova AI Workspace"
        )

        worksheet["A4"] = "Content"

        # -----------------------------------------------------
        # Content rows
        # -----------------------------------------------------

        paragraphs = [
            paragraph.strip()
            for paragraph in str(content).split("\n")
            if paragraph.strip()
        ]

        if not paragraphs:
            paragraphs = [
                str(content).strip()
            ]

        row = 5

        for paragraph in paragraphs:
            worksheet.cell(
                row=row,
                column=1,
                value=paragraph,
            )
            row += 1

        # -----------------------------------------------------
        # Basic formatting
        # -----------------------------------------------------

        title_font = copy(
            worksheet["A1"].font
        )
        title_font.bold = True
        title_font.size = 16

        worksheet["A1"].font = title_font

        subtitle_font = copy(
            worksheet["A2"].font
        )
        subtitle_font.italic = True

        worksheet["A2"].font = subtitle_font

        header_font = copy(
            worksheet["A4"].font
        )
        header_font.bold = True

        worksheet["A4"].font = header_font

        worksheet.column_dimensions["A"].width = 100

        # -----------------------------------------------------
        # Wrap content text
        # -----------------------------------------------------

        for current_row in worksheet.iter_rows(
            min_row=4,
            max_row=max(row - 1, 4),
            min_col=1,
            max_col=1,
        ):
            alignment = copy(
                current_row[0].alignment
            )

            alignment.wrap_text = True
            alignment.vertical = "top"

            current_row[0].alignment = alignment

        workbook.save(file_path)

        return str(file_path)


def get_content_file_export_service():
    return ContentFileExportService()